### PageRank

In [1]:
import numpy as np

In [2]:
N = 3

ranks = np.array([1.0 / N for _ in range(N)])
trainsition = np.asarray(
    [[0, 1/2., 1/2.],
     [0,    0,    1],
     [0,    1,    0]]
)
teleport = 1.0 / N

In [3]:
P = 0.9 * trainsition + 0.1 * teleport
print(P)

[[0.03333333 0.48333333 0.48333333]
 [0.03333333 0.03333333 0.93333333]
 [0.03333333 0.93333333 0.03333333]]


In [4]:
for i in range(3):
    ranks = np.dot(ranks, P)
print(ranks)

[0.03333333 0.48333333 0.48333333]
